### ISSUE TITLE
About the issue"RuntimeError: CUDA error: device-side assert triggered"

### ISSUE THREAD

**Issue by lixiaofei-sys** [YangXiaocui1215/GMP#5]
I met the problem when I ran the file '17_pretrain_full_for_generated_dual_prompts_multitasks_Aspect.sh', how can I solve the problem? Thank you very much!!!
`/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "MAESC_training_for_generated_dual_prompts_multitasks_Aspect.py", line 438, in <module>
    main(0, args)
  File "MAESC_training_for_generated_dual_prompts_multitasks_Aspect.py", line 220, in main
    res_test, test_aspects_num_acc = eval_utils.eval(args, model, test_loader, metric,device)
  File "/home/jncsnlp/lxf/GMP-main/src/eval_utils_multitasks.py", line 25, in eval
    predict, predict_aspects_num = model.predict(
  File "/home/jncsnlp/lxf/GMP-main/src/model/generater_for_generated_prompt_multitasks.py", line 119, in predict
    state, aspects_num_loss, predict_aspects_num = self.seq2seq_model.prepare_state(
  File "/home/jncsnlp/lxf/GMP-main/src/model/MAESC_model_for_generated_dual_prompts_multitasks_Aspect.py", line 249, in prepare_state
    dict = self.encoder(
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jncsnlp/lxf/GMP-main/src/model/modules_for_prompt_multitasks.py", line 900, in forward
    inputs_embeds = self._embed_multi_modal(generated_aspect_prompt, generated_senti_prompt, aspects_num,
  File "/home/jncsnlp/lxf/GMP-main/src/model/modules_for_prompt_multitasks.py", line 731, in _embed_multi_modal
    embedded_images = self.embed_images(image_features)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jncsnlp/lxf/GMP-main/src/model/modules_for_prompt_multitasks.py", line 125, in forward
    image_features = encode_images(image_encoder=image_encoder, 
  File "/home/jncsnlp/lxf/GMP-main/src/model/modules_for_prompt_multitasks.py", line 92, in encode_images
    visual = image_encoder(pixel_values)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/timm/models/nfnet.py", line 567, in forward
    x = self.forward_features(x)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/timm/models/nfnet.py", line 560, in forward_features
    x = self.stem(x)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/timm/models/layers/std_conv.py", line 99, in forward
    return F.conv2d(x, self.get_weight(), self.bias, self.stride, self.padding, self.dilation, self.groups)
  File "/home/jncsnlp/anaconda3/envs/gmp/lib/python3.8/site-packages/timm/models/layers/std_conv.py", line 94, in get_weight
    std, mean = torch.std_mean(self.weight, dim=[1, 2, 3], keepdim=True, unbiased=False)
RuntimeError: CUDA error: device-side assert triggered`

**Comment by ShenXudong666** [comment]
放了其他的数据后，我也出现了这个错误，请问您解决了吗
